server:
  port: 9091
  
spring:
  application:
    name: h-springcloud-sidecar-web
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@eureka1.ec.bwoil.com:8761/eureka/,http://pig:gip6666@eureka2.ec.bwoil.com:8761/eureka/,http://pig:gip6666@eureka3.ec.bwoil.com:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: ${eureka-interval:5}
    prefer-ip-address: true