server:
  port: 9090
  
spring:
  application:
    name: h-springcloud-sidecar-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@eureka1.ec.bwoil.com:8761/eureka/,http://pig:gip6666@eureka2.ec.bwoil.com:8761/eureka/,http://pig:gip6666@eureka3.ec.bwoil.com:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: ${eureka-interval:5}
    prefer-ip-address: true

sidecar:
  port: 3000
  health-uri: http://localhost:${sidecar.port}/health.json
  home-page-uri: http://localhost:${sidecar.port}
